# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=5000)),
                ('picture', models.URLField()),
            ],
        ),
    ]
