# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 02:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='picture',
            new_name='url',
        ),
    ]
