# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 00:32
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20160423_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='photos'),
        ),
    ]
